dist: jammy
language: node_js
services:
  - redis-server
  - rabbitmq
env:
  - NODE_ENV=development BUHOI_REDIS=redis://localhost BUHOI_MQ=amqp://guest:guest@localhost
node_js:
  - "18"
script: npm run travis-coveralls
